<a href="https://colab.research.google.com/github/uuuujisu/practice_colab/blob/master/packages.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy** package

In [ ]:
import numpy as np

In [ ]:
matrix_a = np.asarray([[4, 5, 2],
                       [5, 2, 6],
                       [6, 1, -2]])

matrix_b = np.asarray([[5, 9, 2],
                       [2, 0, 3],
                       [1, -4, 5]])

matrix_c = matrix_a + matrix_b
print(matrix_c)

[[ 9 14  4]
 [ 7  2  9]
 [ 7 -3  3]]


**Pandas** package

In [ ]:
import pandas as pd

In [ ]:
col_id = pd.Series(data=[5, 14, 21, 25])
col_team = pd.Series(data=['A', 'A', 'B', 'B'])
col_name = pd.Series(data=['김패캠', '정코딩', '박데사', '장머신'])
col_score = pd.Series(data=[100, 95, 60, 80])

df = pd.DataFrame(data={'id' : col_id,
                        'team' : col_team,
                        'name' : col_name,
                        'score' : col_score})
df.set_index('id',inplace=True)
df

team name  score
id                 
5     A  김패캠    100
14    A  정코딩     95
21    B  박데사     60
25    B  장머신     80

In [ ]:
df.groupby('team').mean()

score
team       
A      97.5
B      70.0